export interface MediaItem {
  id: string;
  title: string;
  category: "images" | "videos" | "music" | "sfx";
  url: string;
  thumbnailUrl?: string;
  duration?: string | number;
  dimensions?: string;
  fileSize?: string;
  format?: string;
  tags: string[];
}

export const MOCK_MEDIA_ITEMS: MediaItem[] = [
  // Images
  {
    id: "media-img-1",
    title: "Luxury Modern Villa Exterior",
    category: "images",
    url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&auto=format&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&auto=format&fit=crop&q=80",
    dimensions: "3840x2160",
    fileSize: "3.4 MB",
    format: "JPG",
    tags: ["architecture", "luxury", "villa", "modern", "exterior"],
  },
  {
    id: "media-img-2",
    title: "Minimalist Italian Chef Kitchen",
    category: "images",
    url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&auto=format&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&auto=format&fit=crop&q=80",
    dimensions: "3840x2160",
    fileSize: "2.8 MB",
    format: "JPG",
    tags: ["interior", "kitchen", "luxury", "home"],
  },
  {
    id: "media-img-3",
    title: "Executive Master Bedroom Suite",
    category: "images",
    url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600&auto=format&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&auto=format&fit=crop&q=80",
    dimensions: "3840x2160",
    fileSize: "3.1 MB",
    format: "JPG",
    tags: ["interior", "bedroom", "suite", "sunset"],
  },
  {
    id: "media-img-4",
    title: "AI Analytics & SaaS Dashboard Visual",
    category: "images",
    url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1600&auto=format&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&auto=format&fit=crop&q=80",
    dimensions: "3840x2160",
    fileSize: "2.1 MB",
    format: "PNG",
    tags: ["tech", "dashboard", "analytics", "saas"],
  },
  {
    id: "media-img-5",
    title: "Futuristic Neon Cyberpunk Alley",
    category: "images",
    url: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&auto=format&fit=crop&q=80",
    dimensions: "3840x2160",
    fileSize: "4.2 MB",
    format: "JPG",
    tags: ["cyberpunk", "neon", "night", "city", "future"],
  },
  {
    id: "media-img-6",
    title: "Creative Agency Studio Workspace",
    category: "images",
    url: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1600&auto=format&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=400&auto=format&fit=crop&q=80",
    dimensions: "3840x2160",
    fileSize: "2.5 MB",
    format: "JPG",
    tags: ["workspace", "office", "studio", "business"],
  },
  {
    id: "media-img-7",
    title: "Abstract Fluid Gradient Neon Sphere",
    category: "images",
    url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1600&auto=format&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80",
    dimensions: "3840x2160",
    fileSize: "3.6 MB",
    format: "PNG",
    tags: ["3d", "abstract", "gradient", "sphere", "minimal"],
  },
  {
    id: "media-img-8",
    title: "Tech Startup Team Collaboration",
    category: "images",
    url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1600&auto=format&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400&auto=format&fit=crop&q=80",
    dimensions: "3840x2160",
    fileSize: "3.0 MB",
    format: "JPG",
    tags: ["team", "collaboration", "startup", "people"],
  },

  // Stock Videos
  {
    id: "media-vid-1",
    title: "Abstract Neural Flow Motion Loop",
    category: "videos",
    url: "https://assets.mixkit.co/videos/preview/mixkit-circuit-board-micro-controller-view-41738-large.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&auto=format&fit=crop&q=80",
    duration: 15,
    dimensions: "1920x1080",
    fileSize: "12.4 MB",
    format: "MP4",
    tags: ["motion", "circuit", "tech", "data", "ai"],
  },
  {
    id: "media-vid-2",
    title: "Golden Hour Ocean Drone Sweep",
    category: "videos",
    url: "https://assets.mixkit.co/videos/preview/mixkit-aerial-view-of-sea-waves-reaching-the-beach-41525-large.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&auto=format&fit=crop&q=80",
    duration: 20,
    dimensions: "1920x1080",
    fileSize: "18.2 MB",
    format: "MP4",
    tags: ["nature", "ocean", "drone", "cinematic", "waves"],
  },
  {
    id: "media-vid-3",
    title: "Modern Glass Skyscraper Clouds Time-lapse",
    category: "videos",
    url: "https://assets.mixkit.co/videos/preview/mixkit-modern-buildings-in-a-financial-district-41444-large.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400&auto=format&fit=crop&q=80",
    duration: 14,
    dimensions: "1920x1080",
    fileSize: "14.1 MB",
    format: "MP4",
    tags: ["city", "architecture", "business", "clouds"],
  },

  // Royalty Free Music Tracks
  {
    id: "media-mus-1",
    title: "Ambient Future Chillwave",
    category: "music",
    url: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=ambient-piano-10781.mp3",
    duration: 142,
    fileSize: "3.8 MB",
    format: "MP3",
    tags: ["ambient", "piano", "chill", "calm", "tech"],
  },
  {
    id: "media-mus-2",
    title: "Upbeat Corporate Innovation",
    category: "music",
    url: "https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3?filename=corporate-motivational-background-music-111000.mp3",
    duration: 120,
    fileSize: "3.2 MB",
    format: "MP3",
    tags: ["upbeat", "corporate", "energetic", "presentation", "saas"],
  },
  {
    id: "media-mus-3",
    title: "Cinematic Pulse & Tension",
    category: "music",
    url: "https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f792cb.mp3?filename=epic-cinematic-trailer-124036.mp3",
    duration: 98,
    fileSize: "2.6 MB",
    format: "MP3",
    tags: ["cinematic", "epic", "trailer", "motion", "bass"],
  },
  {
    id: "media-mus-4",
    title: "Lo-Fi Midnight Study Beat",
    category: "music",
    url: "https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3?filename=lofi-study-112191.mp3",
    duration: 154,
    fileSize: "4.1 MB",
    format: "MP3",
    tags: ["lofi", "beats", "relax", "youtube", "reels"],
  },

  // Sound Effects
  {
    id: "media-sfx-1",
    title: "Smooth Whoosh Transition",
    category: "sfx",
    url: "https://cdn.pixabay.com/download/audio/2022/03/10/audio_c3523e4210.mp3?filename=whoosh-6316.mp3",
    duration: 2,
    fileSize: "45 KB",
    format: "WAV",
    tags: ["whoosh", "transition", "swipe", "fast"],
  },
  {
    id: "media-sfx-2",
    title: "Subtle Interface Click / Pop",
    category: "sfx",
    url: "https://cdn.pixabay.com/download/audio/2022/03/15/audio_2478ef991c.mp3?filename=pop-39222.mp3",
    duration: 1,
    fileSize: "18 KB",
    format: "WAV",
    tags: ["click", "pop", "ui", "button"],
  },
  {
    id: "media-sfx-3",
    title: "Camera Shutter Click",
    category: "sfx",
    url: "https://cdn.pixabay.com/download/audio/2021/08/04/audio_bb630cc098.mp3?filename=camera-shutter-click-01.mp3",
    duration: 1,
    fileSize: "24 KB",
    format: "WAV",
    tags: ["camera", "snap", "shutter", "photo"],
  },
  {
    id: "media-sfx-4",
    title: "Sci-Fi Data Beep & Sparkle",
    category: "sfx",
    url: "https://cdn.pixabay.com/download/audio/2022/03/15/audio_51a37c95e1.mp3?filename=sci-fi-click-90417.mp3",
    duration: 2,
    fileSize: "62 KB",
    format: "WAV",
    tags: ["tech", "scifi", "beep", "sparkle", "ai"],
  },
];

export const STYLE_PRESETS = [
  { id: "cinematic", label: "Cinematic 8K", desc: "Photorealistic lighting, anamorphic lens flare & depth" },
  { id: "studio-portrait", label: "Studio Portrait", desc: "Crisp 85mm portrait with soft diffused key light" },
  { id: "minimal-3d", label: "Minimalist 3D", desc: "Clean isometric matte 3D render with soft ambient occlusion" },
  { id: "cyberpunk", label: "Cyberpunk Neon", desc: "Vibrant magenta & cyan neon glow with rain reflections" },
  { id: "luxury-real-estate", label: "Luxury Architectural", desc: "Warm interior lighting and wide-angle architectural perspective" },
  { id: "anime-studio", label: "Anime Masterpiece", desc: "Vibrant Makoto Shinkai style sky and rich cel shading" },
];

export const MOTION_PRESET_METADATA = [
  {
    id: "zoom-in",
    label: "Zoom In",
    desc: "Smooth continuous camera push towards center focus",
    icon: "ZoomIn",
    category: "zoom",
  },
  {
    id: "zoom-out",
    label: "Zoom Out",
    desc: "Gentle pull-back revealing surrounding landscape",
    icon: "ZoomOut",
    category: "zoom",
  },
  {
    id: "pan-left",
    label: "Pan Left",
    desc: "Horizontal lateral track across the visual plane to the left",
    icon: "ArrowLeft",
    category: "pan",
  },
  {
    id: "pan-right",
    label: "Pan Right",
    desc: "Horizontal lateral track across the visual plane to the right",
    icon: "ArrowRight",
    category: "pan",
  },
  {
    id: "pan-up",
    label: "Pan Up",
    desc: "Vertical tilt upward exploring height and architectural ceiling",
    icon: "ArrowUp",
    category: "pan",
  },
  {
    id: "pan-down",
    label: "Pan Down",
    desc: "Vertical tilt downward guiding eye toward foreground subjects",
    icon: "ArrowDown",
    category: "pan",
  },
  {
    id: "slow-zoom",
    label: "Slow Zoom",
    desc: "Subtle, imperceptible 3% zoom drift for premium documentaries",
    icon: "Scan",
    category: "subtle",
  },
  {
    id: "cinematic-push",
    label: "Cinematic Push",
    desc: "Dynamic forward dolly push with slight perspective tilt",
    icon: "Maximize",
    category: "dramatic",
  },
  {
    id: "cinematic-pull",
    label: "Cinematic Pull",
    desc: "Dramatic wide reveal pulling back with subtle drift",
    icon: "Minimize",
    category: "dramatic",
  },
  {
    id: "none",
    label: "Static Frame",
    desc: "Fixed tripod perspective with zero camera drift",
    icon: "Square",
    category: "static",
  },
] as const;
